set_global_assignment -entity "clock_12MHz" -library "lib_clock_12MHz" -name IP_TOOL_NAME "altera_pll"
set_global_assignment -entity "clock_12MHz" -library "lib_clock_12MHz" -name IP_TOOL_VERSION "21.1"
set_global_assignment -entity "clock_12MHz" -library "lib_clock_12MHz" -name IP_TOOL_ENV "mwpim"
set_global_assignment -library "lib_clock_12MHz" -name SPD_FILE [file join $::quartus(sip_path) "clock_12MHz.spd"]

set_global_assignment -library "lib_clock_12MHz" -name MISC_FILE [file join $::quartus(sip_path) "clock_12MHz_sim/clock_12MHz.vho"]
